
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'router'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'regions'
    static_configs:
      - targets:
        - 'localhost:2112'
        - 'localhost:2113'
        - 'localhost:2114'
